# This workflow is triggered on pushes to the main branch and on manual workflow dispatch.
# It logs in to the GitHub Container Registry and builds and pushes a dev container image.

name: "(Release) Release dev container templates"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build image and run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/josiahsiegel/devops-image
          push: always
